server:
  port: 8281
spring:
  application:
    name: payService
  cloud:
      nacos:
        server-addr: localhost:8848

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_order
    username: postgres
    password: xujian123
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.elio.hotel.pojo
logging:
  level:
    com.elio: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#开启饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: userService,hotelService,roomService # 项目启动时直接去拉取userservice的集群，多个用","隔开